### ISSUE TITLE
cant able to import the package

### ISSUE THREAD

**Issue by Wreaking** [warix8/discord-bot-stats#9]
![image](https://user-images.githubusercontent.com/81316640/183304373-6bad9a4d-2984-48ad-a2c5-a66b9c6aad17.png)

**Comment by warix8** [comment]
Glad to know that you want to use my module 😄 

It seems that there is a problem with the canvas installation.
Maybe you can try to install canvas first.
I assume that you are on Windows, so you can check this canvas guide for windows installation https://github.com/Automattic/node-canvas/wiki/Installation:-Windows

I hope this will solve your problem

**Comment by Wreaking** [comment]
> Glad to know that you want to use my module 😄
> 
> It seems that there is a problem with the canvas installation. Maybe you can try to install canvas first. I assume that you are on Windows, so you can check this canvas guide for windows installation https://github.com/Automattic/node-canvas/wiki/Installation:-Windows
> 
> I hope this will solve your problem

**Comment by Wreaking** [comment]
wait, isnt canvas outdated package? i heard about it in djs supportive server

**Comment by Wreaking** [comment]
didnt work while following the steps to download canvas in https://www.youtube.com/watch?v=SletQOmrhcM

**Comment by warix8** [comment]
Are you sure that node-gyp is installed ? https://github.com/nodejs/node-gyp#on-windows

If yes, can you give me your:

- NodeJs version
- node-gyp version

**Comment by Wreaking** [comment]
my node.js version 18.4.0
i am not familiar with node-gyp and python tbh

**Comment by warix8** [comment]
It's really strange, but you can try a node-gyp rebuild then if it's not working try this

npm uninstall node-pre-gyp -g --save
npm install @mapbox/node-pre-gyp -g --save

**Comment by Wreaking** [comment]
well its not working either. could u use other packages rather using canvas like canvacord?

**Comment by warix8** [comment]
It's a bit hard, because I'm using chart.js to make graph and it depends of canvas. 

But, I'm sure that you can fix your issue by searching your errors on Internet et try some fixes. 

Nevertheless, I will have a look if I can fork chartjs and try to use an other canvas like canvacord.

**Comment by Wreaking** [comment]
okay i will try to fix it thx
